// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IPoseidon
 * @notice Interface for Poseidon hash function (ZK-friendly)
 */
interface IPoseidon {
    function poseidon(uint256[2] calldata inputs) external pure returns (uint256);
    function poseidon(uint256[3] calldata inputs) external pure returns (uint256);
}

/**
 * @title ITransferVerifier
 * @notice Interface for the auto-generated Groth16 verifier of the
 *         transfer circuit (3 public signals: root, nullifierHash,
 *         newCommitment).
 * @dev Generated by `snarkjs zkey export solidityverifier transfer_final.zkey`.
 *      The pubSignals array is fixed-size [3] — must match the circuit
 *      output count exactly.
 */
interface ITransferVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[3] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IUnshieldVerifier
 * @notice Interface for the auto-generated Groth16 verifier of the
 *         unshield circuit. Seven public signals in this exact order,
 *         matching circuits/core/unshield.circom's `component main`
 *         declaration:
 *           [0] root
 *           [1] nullifierHash
 *           [2] recipient (address as uint256)
 *           [3] relayer   (address as uint256)
 *           [4] tokenId
 *           [5] amount
 *           [6] fee
 * @dev Audit Issue 4 (High): the relayer is now bound into the proof
 *      so an MEV attacker can't take a victim's pending withdraw and
 *      swap `_relayer` to their own address to steal the fee. The
 *      circuit was updated in atoshi-privacy-circuits commit 79af18b.
 */
interface IUnshieldVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[7] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IShieldVerifier
 * @notice Interface for the auto-generated Groth16 verifier of the
 *         shield (deposit) circuit. Three public signals matching
 *         circuits/core/shield.circom output order:
 *           [0] commitment — the Poseidon-hashed note commitment
 *           [1] amount     — token amount (must equal on-chain _amount)
 *           [2] tokenId    — ERC-20 contract address cast to uint256
 *                            (0 for the native token)
 * @dev Audit Issue 2 (High): the shield circuit was updated to expose
 *      `amount` and `tokenId` as public inputs so the deposit contract
 *      can cross-check them against the actual on-chain transfer,
 *      preventing the "deposit 1 wei but commit 1000 tokens" attack.
 */
interface IShieldVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[3] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IShield
 * @notice Interface for Shield contract
 */
interface IShield {
    // Events
    /// @dev encryptedNote 是 ECIES 加密的 Note 数据(amount,blinding,...),
    ///      接收方用自己的 viewingKey 解密即可恢复 Note. 链下生成,合约不解读.
    ///      允许空(向后兼容,但前端建议总是带上以支持跨设备恢复).
    event Deposit(
        uint256 indexed commitment,
        uint256 leafIndex,
        uint256 timestamp,
        address indexed token,
        uint256 amount,
        bytes encryptedNote
    );

    event Withdrawal(
        address indexed recipient,
        uint256 indexed nullifierHash,
        address indexed relayer,
        uint256 fee
    );

    event Transfer(
        uint256 indexed nullifierHash,
        uint256 indexed newCommitment,
        bytes encryptedNote
    );

    // Functions
    function deposit(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256 commitment,
        address token,
        uint256 amount,
        bytes calldata encryptedNote
    ) external payable;

    function withdraw(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256 _root,
        uint256 _nullifierHash,
        address _recipient,
        address _relayer,
        uint256 _fee,
        address _token,
        uint256 _amount
    ) external;

    function isKnownRoot(uint256 _root) external view returns (bool);
    function isSpent(uint256 _nullifierHash) external view returns (bool);
}

