// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "../interfaces/IShield.sol"; // also brings in IPoseidon
import "../libraries/MerkleTree.sol";
// Poseidon hashing is delegated to an external contract whose bytecode
// is generated by circomlibjs at deploy time. The legacy
// libraries/Poseidon.sol is a keccak256 placeholder and is no longer
// imported here; it can be removed in a follow-up cleanup.

/**
 * @notice Minimal interface to the EnergySettlement contract. The
 *         transfer path needs isRegistered to avoid reverting normal
 *         user-broadcast transfers; withdraw uses consumeForRelayer
 *         unconditionally (the explicit `_relayer` param signals
 *         intent).
 */
interface IEnergySettlement {
    function consumeForRelayer(address relayer, uint256 gasUsed) external;
    function isRegistered(address relayer) external view returns (bool);
}

/**
 * @title Shield
 * @notice Main privacy pool contract for Atoshi Chain
 * @dev Implements deposit/withdraw functionality with ZK proof verification
 * 
 * Architecture:
 * - Users deposit tokens and receive a commitment (stored in Merkle tree)
 * - Users can withdraw by providing a valid ZK proof
 * - Nullifiers prevent double-spending
 * - Supports native token (ATOS) and ERC20 tokens
 * 
 * Note Structure (off-chain):
 * - commitment = Poseidon(amount, token, pubKey, blinding)
 * - nullifier = Poseidon(commitment, privKey, leafIndex)
 */
contract Shield is IShield, ReentrancyGuard, Ownable {
    using SafeERC20 for IERC20;
    using MerkleTree for MerkleTree.TreeData;

    // ============ Constants ============
    
    uint256 public constant FIELD_SIZE = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint32 public constant TREE_LEVELS = 20; // Supports 2^20 = ~1M deposits
    uint32 public constant ROOT_HISTORY_SIZE = 100;
    
    // Native token address placeholder
    address public constant NATIVE_TOKEN = address(0);

    // ============ State Variables ============
    
    // Verifier contracts for ZK proofs. We have one per circuit because
    // each circuit has a different number of public signals — the generated
    // verifyProof() signature is statically typed (uint256[N] calldata),
    // so a single contract address can't serve all paths.
    address public transferVerifier;  // 3 public signals
    address public unshieldVerifier;  // 6 public signals

    // External Poseidon hash contract (bytecode from circomlibjs at deploy
    // time). Used for both Merkle parent hashing inside MerkleTree and
    // for the zero-subtree initialization below.
    address public poseidonContract;

    // Optional EnergySettlement contract. When set, withdraw() and
    // transfer() consume the relayer's L1-derived quota. When the
    // address is 0 the privacy stack works in "self-paid" mode where
    // each relayer simply pays L2 gas out of pocket. The flag is
    // mutable by the owner so we can disable it during incidents.
    address public energySettlement;
    // Per-tx gas charge attributed to the relayer for a withdraw. Not
    // the actual gas_used (that is unknown until the tx finishes); a
    // governance-tunable allowance instead. Defaults set in constructor
    // and tweakable via setRelayerGasCharge.
    uint256 public withdrawGasCharge;
    uint256 public transferGasCharge;
    
    // Merkle tree for commitments
    MerkleTree.TreeData private commitmentTree;
    
    // Nullifier registry (nullifierHash => spent)
    mapping(uint256 => bool) public nullifierHashes;
    
    // Token whitelist (token => enabled)
    mapping(address => bool) public supportedTokens;
    
    // Minimum deposit amounts per token
    mapping(address => uint256) public minDeposits;
    
    // Protocol fee (basis points, e.g., 30 = 0.3%)
    uint256 public protocolFeeBps;
    address public feeRecipient;
    
    // Emergency pause
    bool public paused;

    // Zero values for Merkle tree initialization
    uint256[] private zeros;

    // ============ Modifiers ============
    
    modifier whenNotPaused() {
        require(!paused, "Shield: paused");
        _;
    }
    
    modifier validToken(address _token) {
        require(supportedTokens[_token], "Shield: unsupported token");
        _;
    }

    // ============ Constructor ============
    
    /**
     * @notice Initialize the Shield contract
     * @param _transferVerifier Verifier for the private-transfer circuit
     *        (3 public signals: root, nullifierHash, newCommitment)
     * @param _unshieldVerifier Verifier for the unshield/withdraw circuit
     *        (6 public signals: root, nullifierHash, recipient, tokenId,
     *        amount, fee)
     * @param _poseidon Address of the deployed real-Poseidon contract
     *        (bytecode generated by circomlibjs.poseidonContract.createCode(2))
     *        used for Merkle parent hashing. MUST match the hash function
     *        the off-chain circuit uses, otherwise ZK proofs will not
     *        verify.
     * @param _feeRecipient Address to receive protocol fees
     */
    constructor(
        address _transferVerifier,
        address _unshieldVerifier,
        address _poseidon,
        address _feeRecipient
    ) Ownable(msg.sender) {
        require(_transferVerifier != address(0), "Shield: invalid transfer verifier");
        require(_unshieldVerifier != address(0), "Shield: invalid unshield verifier");
        require(_poseidon != address(0), "Shield: invalid poseidon address");

        transferVerifier = _transferVerifier;
        unshieldVerifier = _unshieldVerifier;
        poseidonContract = _poseidon;
        feeRecipient = _feeRecipient;
        protocolFeeBps = 30; // 0.3% default fee

        // Defaults sized for a 20-level Merkle proof verification + the
        // Groth16 pairing. Real measurements: withdraw ≈ 800k, transfer
        // ≈ 750k. The owner can re-tune via setRelayerGasCharge.
        withdrawGasCharge = 1_000_000;
        transferGasCharge = 1_000_000;

        // Initialize zero values for Merkle tree (calls IPoseidon)
        _initializeZeros();

        // Initialize Merkle tree (passes poseidon address for parent hashing)
        commitmentTree.initialize(TREE_LEVELS, ROOT_HISTORY_SIZE, zeros, _poseidon);
        
        // Enable native token by default
        supportedTokens[NATIVE_TOKEN] = true;
    }

    // ============ External Functions ============
    
    /**
     * @notice Deposit tokens into the privacy pool
     * @param _commitment The commitment hash (computed off-chain)
     * @param _token Token address (address(0) for native token)
     * @param _amount Amount to deposit
     */
    function deposit(
        uint256 _commitment,
        address _token,
        uint256 _amount
    ) external payable override nonReentrant whenNotPaused validToken(_token) {
        require(_commitment < FIELD_SIZE, "Shield: invalid commitment");
        require(_amount >= minDeposits[_token], "Shield: amount too small");
        
        // Handle token transfer
        if (_token == NATIVE_TOKEN) {
            require(msg.value == _amount, "Shield: incorrect native amount");
        } else {
            require(msg.value == 0, "Shield: unexpected native token");
            IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
        }
        
        // Insert commitment into Merkle tree
        uint32 leafIndex = commitmentTree.insert(_commitment);
        
        emit Deposit(_commitment, leafIndex, block.timestamp, _token, _amount);
    }

    /**
     * @notice Withdraw tokens from the privacy pool
     * @param _pA Proof element A
     * @param _pB Proof element B
     * @param _pC Proof element C
     * @param _root Merkle root used in proof
     * @param _nullifierHash Nullifier hash to prevent double-spend
     * @param _recipient Address to receive tokens
     * @param _relayer Relayer address (for gas abstraction)
     * @param _fee Fee to pay relayer
     * @param _token Token to withdraw
     * @param _amount Amount to withdraw
     */
    function withdraw(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256 _root,
        uint256 _nullifierHash,
        address _recipient,
        address _relayer,
        uint256 _fee,
        address _token,
        uint256 _amount
    ) external override nonReentrant whenNotPaused validToken(_token) {
        require(_nullifierHash < FIELD_SIZE, "Shield: invalid nullifier");
        require(!nullifierHashes[_nullifierHash], "Shield: already spent");
        require(isKnownRoot(_root), "Shield: unknown root");
        require(_recipient != address(0), "Shield: invalid recipient");
        require(_fee <= _amount, "Shield: fee exceeds amount");
        
        // Verify ZK proof against the unshield circuit verifier.
        // Public inputs (must match circuits/unshield.circom output order):
        //   [0] root
        //   [1] nullifierHash
        //   [2] recipient (address as uint256)
        //   [3] tokenId / token address as uint256
        //   [4] amount
        //   [5] fee
        uint256[6] memory pubSignals = [
            _root,
            _nullifierHash,
            addressToUint256(_recipient),
            addressToUint256(_token),
            _amount,
            _fee
        ];

        require(
            IUnshieldVerifier(unshieldVerifier).verifyProof(_pA, _pB, _pC, pubSignals),
            "Shield: invalid proof"
        );
        
        // Mark nullifier as spent
        nullifierHashes[_nullifierHash] = true;

        // If an EnergySettlement is configured AND the broadcaster is a
        // registered relayer, charge the relayer's L1-derived quota
        // for this withdraw. Reverts if the relayer has run out of
        // budget — fail-loud so off-chain operators top up promptly.
        // Self-paid mode is the default in tests / standalone deploys.
        if (energySettlement != address(0) && msg.sender == _relayer) {
            IEnergySettlement(energySettlement).consumeForRelayer(_relayer, withdrawGasCharge);
        }

        // Calculate protocol fee
        uint256 protocolFee = (_amount * protocolFeeBps) / 10000;
        uint256 netAmount = _amount - _fee - protocolFee;
        
        // Transfer tokens
        if (_token == NATIVE_TOKEN) {
            // Transfer to recipient
            (bool success1, ) = payable(_recipient).call{value: netAmount}("");
            require(success1, "Shield: native transfer failed");
            
            // Transfer relayer fee
            if (_fee > 0 && _relayer != address(0)) {
                (bool success2, ) = payable(_relayer).call{value: _fee}("");
                require(success2, "Shield: relayer fee transfer failed");
            }
            
            // Transfer protocol fee
            if (protocolFee > 0 && feeRecipient != address(0)) {
                (bool success3, ) = payable(feeRecipient).call{value: protocolFee}("");
                require(success3, "Shield: protocol fee transfer failed");
            }
        } else {
            IERC20(_token).safeTransfer(_recipient, netAmount);
            
            if (_fee > 0 && _relayer != address(0)) {
                IERC20(_token).safeTransfer(_relayer, _fee);
            }
            
            if (protocolFee > 0 && feeRecipient != address(0)) {
                IERC20(_token).safeTransfer(feeRecipient, protocolFee);
            }
        }
        
        emit Withdrawal(_recipient, _nullifierHash, _relayer, _fee);
    }

    /**
     * @notice Private transfer within the pool (spend old note, create new note)
     * @dev This allows transferring ownership without leaving the pool
     */
    function transfer(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256 _root,
        uint256 _nullifierHash,
        uint256 _newCommitment
    ) external nonReentrant whenNotPaused {
        require(_nullifierHash < FIELD_SIZE, "Shield: invalid nullifier");
        require(_newCommitment < FIELD_SIZE, "Shield: invalid commitment");
        require(!nullifierHashes[_nullifierHash], "Shield: already spent");
        require(isKnownRoot(_root), "Shield: unknown root");
        
        // Verify ZK proof against the transfer circuit verifier.
        // Public inputs (transfer.circom output order):
        //   [0] root
        //   [1] nullifierHash (of the input note)
        //   [2] newCommitment (of the output note)
        uint256[3] memory pubSignals = [_root, _nullifierHash, _newCommitment];

        require(
            ITransferVerifier(transferVerifier).verifyProof(_pA, _pB, _pC, pubSignals),
            "Shield: invalid proof"
        );
        
        // Mark old nullifier as spent
        nullifierHashes[_nullifierHash] = true;

        // If a relayer broadcast this transfer, charge their quota.
        // Self-broadcast transfers (where msg.sender is just the
        // owner of the input note and isn't on the relayer registry)
        // skip quota — the user pays L2 gas directly.
        if (
            energySettlement != address(0) &&
            IEnergySettlement(energySettlement).isRegistered(msg.sender)
        ) {
            IEnergySettlement(energySettlement).consumeForRelayer(msg.sender, transferGasCharge);
        }

        // Insert new commitment
        commitmentTree.insert(_newCommitment);

        emit Transfer(_nullifierHash, _newCommitment);
    }

    // ============ View Functions ============
    
    /**
     * @notice Check if a root is in the history
     */
    function isKnownRoot(uint256 _root) public view override returns (bool) {
        return commitmentTree.isKnownRoot(_root);
    }
    
    /**
     * @notice Check if a nullifier has been spent
     */
    function isSpent(uint256 _nullifierHash) public view override returns (bool) {
        return nullifierHashes[_nullifierHash];
    }
    
    /**
     * @notice Get the current Merkle root
     */
    function getLastRoot() public view returns (uint256) {
        return commitmentTree.getLastRoot();
    }
    
    /**
     * @notice Get the next leaf index
     */
    function getNextIndex() public view returns (uint32) {
        return commitmentTree.nextIndex;
    }

    // ============ Admin Functions ============
    
    /**
     * @notice Add a supported token
     */
    function addSupportedToken(
        address _token,
        uint256 _minDeposit
    ) external onlyOwner {
        supportedTokens[_token] = true;
        minDeposits[_token] = _minDeposit;
    }
    
    /**
     * @notice Remove a supported token
     */
    function removeSupportedToken(address _token) external onlyOwner {
        supportedTokens[_token] = false;
    }
    
    /**
     * @notice Update the transfer-circuit verifier contract. Used when
     *         the circuit is re-generated (e.g. after Phase 2 ceremony).
     */
    function setTransferVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "Shield: invalid verifier");
        transferVerifier = _verifier;
    }

    /**
     * @notice Update the unshield-circuit verifier contract.
     */
    function setUnshieldVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "Shield: invalid verifier");
        unshieldVerifier = _verifier;
    }

    /**
     * @notice Plug in (or unplug) the EnergySettlement contract that
     *         tracks relayer quotas. Pass address(0) to fall back to
     *         self-paid mode without redeploying Shield.
     */
    function setEnergySettlement(address _settlement) external onlyOwner {
        energySettlement = _settlement;
    }

    /**
     * @notice Tune the per-tx quota charged against a relayer for
     *         withdraw / transfer respectively. Real measurements
     *         on hardhat: withdraw ~800k, transfer ~750k. Bump the
     *         allowance if the gas cost grows (new circuit, multi-
     *         asset support, etc.).
     */
    function setRelayerGasCharge(uint256 _withdraw, uint256 _transfer) external onlyOwner {
        withdrawGasCharge = _withdraw;
        transferGasCharge = _transfer;
    }

    /**
     * @notice Update protocol fee
     */
    function setProtocolFee(uint256 _feeBps) external onlyOwner {
        require(_feeBps <= 1000, "Shield: fee too high"); // Max 10%
        protocolFeeBps = _feeBps;
    }
    
    /**
     * @notice Update fee recipient
     */
    function setFeeRecipient(address _recipient) external onlyOwner {
        feeRecipient = _recipient;
    }
    
    /**
     * @notice Emergency pause
     */
    function setPaused(bool _paused) external onlyOwner {
        paused = _paused;
    }

    // ============ Internal Functions ============
    
    /**
     * @notice Convert address to uint256
     */
    function addressToUint256(address _addr) internal pure returns (uint256) {
        return uint256(uint160(address(_addr)));
    }
    
    /**
     * @notice Initialize zero values for Merkle tree
     * @dev zeros[i] = hash of empty subtree at level i
     *      zeros[0] = hash of empty leaf
     *      zeros[i] = hash(zeros[i-1], zeros[i-1])
     */
    function _initializeZeros() internal {
        zeros = new uint256[](TREE_LEVELS);
        
        // Start with zero leaf value
        uint256 currentZero = 0;
        
        for (uint32 i = 0; i < TREE_LEVELS; i++) {
            zeros[i] = currentZero;
            // Next level zero = hash(currentZero, currentZero) using the
            // real Poseidon contract. This MUST match the off-chain
            // computation; using keccak256 here would produce different
            // root values from those the SDK computes.
            uint256[2] memory inputs;
            inputs[0] = currentZero;
            inputs[1] = currentZero;
            currentZero = IPoseidon(poseidonContract).poseidon(inputs);
        }
    }

    // ============ Receive Function ============
    
    receive() external payable {
        // Allow receiving native tokens
    }
}

